### ISSUE TITLE
File upload is not working

### ISSUE THREAD

**Issue by jicksonjohnson** [tokarskimarcin/laravel-admin-ext-modal-form#9]
Hello, looks like file upload is not working inside this modal form.

I am trying to include inside a GIRD. For that, I created the ModalButton class and included it in the grid tool

`$grid->tools(function ($tools) use ($quick_create, $bulk_import) {
            if ($bulk_import) {
                $tools->append(new BulkImportTransaction());
            }
 });`

Class "BulkImportTransaction"

`use Encore\Admin\Actions\Action;
use Encore\ModalForm\Form\ModalButton;

class BulkImportTransaction extends Action
{
    protected $selector = '.bulk-import-transaction';

    public function html()
    {
        //creates modal button with `Modal` title and generated route
        $modalButton = new ModalButton('Bulk Import', route('admin.modal.bank-account.transactions.bulk.form'));

        $modalButton->addClass('btn-warning white');

        return $modalButton->render();
    }
}`

Route "admin.modal.bank-account.transactions.bulk.form" pointed to controller and its action is as follows.

`public function modalBulkForm()
    {
        $modalTransaction =  Modal::form(new Transaction(), function (ModalForm $form) {

            $form->large();

            //set action for proper submitting
            $form->setAction(route('admin.modal.bank-account.transactions.form.bulk.store'));

            $bank_accounts = BankAccount::where('status','enabled')
                ->pluck('name','bank_id')->toArray();

            $form->hidden('file_or_single')->default(2); // setting this import as bulk

            $form->select('bank_id', __('Bank Account'))
                ->options($bank_accounts)
                ->rules('required');

            $form->dateRange('start_statement','end_statement')->rules('required');

            $form->decimal('start_balance_file','Starting Balance')->rules('required');

            $form->decimal('close_balance_file','Closing Balance')->rules('required');

            $form->file('file','Upload')->rules('mimes:xls');

        });

        return $modalTransaction->render();
    }`

The Button and Modal with form appear in the browser. There is a file upload field and no issue in browsing the file also.

<img width="1098" alt="Screen Shot 2021-07-08 at 5 39 15 PM" src="https://user-images.githubusercontent.com/15104894/124919189-8aa4f900-e013-11eb-8918-5e1e2b240a14.png">

When I submit the form, there is no file filed in the POST request.

<img width="1680" alt="Screen Shot 2021-07-08 at 5 41 21 PM" src="https://user-images.githubusercontent.com/15104894/124919354-c5a72c80-e013-11eb-8c0a-c6789c90d4b0.png">

Could you please help in fixing this issue?

**Comment by jicksonjohnson** [comment]
Found that, the form content-type is getting changed

from

`multipart/form-data`

to 

`application/x-www-form-urlencoded; charset=UTF-8`

**Comment by tokarskimarcin** [comment]
Glad that you find solution for this
